### ISSUE TITLE
Is it possible to search and replace in the entire project?

### ISSUE THREAD

**Issue by sandangel** [AckslD/muren.nvim#8]
Hi, I'm trying to find how can I do search and replace in the entire project. Can this plugin do that? If not do you plan to add that feature?

**Comment by AckslD** [comment]
Hi @sandangel, no not yet but it's something I [thought](https://github.com/AckslD/muren.nvim#todo) about :) My thinking was that instead of using `s/../..` for each item in the UI we can instead use `:vimgrep`. One thing that might be tricky is the preview but perhaps that could just be disable in this case anyway? Any thoughts?

**Comment by AckslD** [comment]
WIP implementation in #14 if you wanna try. Preview does not work properly yet. Not fully sure what it should show, only the lines or also the filepaths?

**Comment by sandangel** [comment]
Great!! Thankh you very much. I think we can have a look at how spectre.nvim has done. It shows both line and filepath as I remember

**Comment by AckslD** [comment]
Cool, I think that can work. What I don't know is how to enable filetype syntax highlighting in this case so this will probably have to be turned of in this mode. When I find some more time again I'll come back and finish #14. In the meantime if anyone wants to try the current branch feel free to let me know if you have any thoughts already.

**Comment by AckslD** [comment]
I finished #14 so closing this. Let me know if it doesn't work for you for some reason
